import { useEffect, useState } from "react";
import Router from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Edu_QLD_Beginner, Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [username, setUserName] = useState("");
  const [pushLogin, setPushLogin] = useState({});
  let message = "message from Home";

  validateUser();
  // useEffect(() => {
  //   //setUserName(Router.query.username);
  //   //console.log("Home page here ---");
  //   validateUser();
  // }, []);
  useEffect(() => {
    if (pushLogin.push) {
      Router.push(
        {
          pathname: "/login",
          query: {
            message: pushLogin.message,
            authorized: false,
          },
        },
        "/login"
      );
    }
  }, [pushLogin]);
  async function validateUser() {
    try {
      debugger;
      const jsonWebToken = localStorage.getItem("smc_jwtToken");
      const verifyRes = await fetch("/api/verifyJwt", {
        method: "POST",
        body: JSON.stringify({ jsonWebToken }),
      });
      const verifyResponseData = await verifyRes.json();
      const decodedToken = verifyResponseData.decodedToken;

      if (decodedToken.valid) {
        if (!decodedToken.payload.authorized) {
          setPushLogin({
            push: true,
            message: "- authentication failed - please log in -",
          });
        } else {
          setUserName(decodedToken.payload.username);
        }
      } else {
        setPushLogin({
          push: true,
          message: decodedToken.error,
        });
      }
    } catch (error) {
      console.log("home page - validateUser - " + error.message);
    }
  }

  //validateUser();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.js</code>
          </p>
          <p>username: {username}</p>

          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="./vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
                unoptimized
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="./next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  );
}
