import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Edu_QLD_Beginner, Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [username, setUserName] = useState("");
  const [pushLogin, setPushLogin] = useState({});

  const router = useRouter(); // Use useRouter hook here

  useEffect(() => {
    if (pushLogin.push && router) {
      router.push(
        {
          pathname: "/login",
          query: {
            message: pushLogin.message,
            authorized: false,
          },
        },
        "/login"
      );
    }
  }, [pushLogin, router]);
  useEffect(() => {
    //setUserName(Router.query.username);
    //console.log("Home page here ---");
    validateUser();
  }, []);

  async function validateUser() {
    try {
      //debugger;
      const jsonWebToken = localStorage.getItem("smc_jwtToken");
      if (jsonWebToken) {
        const verifyRes = await fetch("/api/verifyJwt", {
          method: "POST",
          body: JSON.stringify({ jsonWebToken }),
        });
        const verifyResponseData = await verifyRes.json();
        const decodedToken = verifyResponseData.decodedToken;

        if (decodedToken.valid) {
          if (!decodedToken.payload.authorized) {
            setPushLogin({
              push: true,
              message: "- authentication failed - please log in -",
            });
          } else {
            setUserName(decodedToken.payload.username);
          }
        } else {
          setPushLogin({
            push: true,
            message: decodedToken.error,
          });
        }
      } else {
        setPushLogin({
          push: true,
          message: "User Credential needed..",
        });
      }
    } catch (error) {
      console.log("home page - validateUser - " + error.message);
    }
  }

  const logoutOnClick = () => {
    localStorage.removeItem("smc_jwtToken");
    setPushLogin({
      push: true,
      message: "logout Successful..!",
    });
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* update favicon */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <p className="text-3xl font-bold underline">username: {username}</p>
          <button
            className="m-1 bg-lime-500 px-2 py-1 rounded hover:bg-lime-600"
            onClick={logoutOnClick}
          >
            Logout
          </button>
        </div>
      </main>
    </>
  );
}
